# -*- coding: utf-8 -*-
"""2548547_ETE.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NOSr-thHu21YxfcglJV4DUVxphi1WCAK

# Medical Image Denoising

Domain: Healthcare and Wellbeing
Topic: Denoising Chest X-Ray Images using a U-Net Autoencoder
"""

# =====================================================================
# CELL 1 — Install Dependencies
# =====================================================================
# !pip install tensorflow scikit-image kagglehub

# =====================================================================
# CELL 2 — Problem Formulation (Markdown Cell in Colab)
# =====================================================================
"""
## Problem Formulation and Understanding

**Domain**: Healthcare and Wellbeing

**Problem**: Medical imaging equipment, especially portable and low-cost X-ray
machines used in rural and resource-limited hospitals, produce noisy images.
This noise can obscure critical diagnostic features — hairline fractures,
early-stage pneumonia opacities, subtle nodules — potentially leading to
misdiagnosis. Automated denoising of medical images is a pressing clinical need.

**Input**: A corrupted chest X-ray image x̃ = x + ε where ε represents
additive noise (Gaussian, impulse, or block corruption). Each image is a
128×128×1 grayscale tensor with pixel values normalized to [0, 1].

**Expected Output**: A clean reconstructed X-ray image x̂ of the same
dimensions (128×128×1), with noise artifacts removed while preserving
diagnostically relevant structures (lung fields, cardiac silhouette,
rib edges, mediastinal contours).

**Learning Task Type**: Unsupervised representation learning — a denoising
autoencoder with skip connections (U-Net) trained via a combined MSE + SSIM
reconstruction objective.

**Why U-Net over a plain Autoencoder?**
A standard autoencoder forces ALL information through a narrow bottleneck,
destroying fine anatomical detail. A U-Net adds skip connections that pass
encoder features directly to the decoder, so fine structures (rib edges,
bronchial patterns, hairline fractures) are preserved while the bottleneck
still learns to separate noise from anatomy.

**Real-World Relevance**:
- Portable X-ray machines in field hospitals produce noisy low-dose images
- Low-dose CT protocols increase quantum noise in reconstructed slices
- X-rays transmitted over low-bandwidth networks suffer compression artifacts
- WHO estimates 2/3 of the global population lacks access to quality radiology
"""

# =====================================================================
# CELL 3 — Imports and GPU Check
# =====================================================================
import numpy as np
import matplotlib.pyplot as plt
import tensorflow as tf
from tensorflow.keras.models import Model
from tensorflow.keras.layers import (
    Input, Conv2D, MaxPooling2D, UpSampling2D,
    BatchNormalization, Activation, Dropout, Concatenate
)
from tensorflow.keras.callbacks import (
    EarlyStopping, ReduceLROnPlateau, ModelCheckpoint
)
from skimage.metrics import peak_signal_noise_ratio as psnr
from skimage.metrics import structural_similarity as ssim
import json, os
from PIL import Image, ImageEnhance, ImageFilter
import kagglehub

print("TensorFlow version:", tf.__version__)
gpus = tf.config.list_physical_devices('GPU')
print("GPU available:", gpus)
if gpus:
    print(f"GPU name: {gpus[0].name}")

# Reproducibility
np.random.seed(42)
tf.random.set_seed(42)

# =====================================================================
# CELL 4 — Download and Load Dataset
# =====================================================================
# Dataset: Kaggle Chest X-Ray Pneumonia
# Source: Guangzhou Women and Children's Medical Center
# 5,856 real pediatric chest X-ray images (NORMAL + PNEUMONIA)
# For denoising, class labels are irrelevant — the model learns to
# reconstruct clean anatomy regardless of diagnosis.

path = kagglehub.dataset_download("paultimothymooney/chest-xray-pneumonia")
print("Dataset path:", path)

IMG_SIZE = 128

def load_images(folder):
    """Load all images from folder tree → grayscale, resized, normalized."""
    images = []
    for root, _, files in os.walk(folder):
        for f in sorted(files):
            if f.lower().endswith(('.jpeg', '.jpg', '.png')):
                img = Image.open(os.path.join(root, f)).convert('L')
                img = img.resize((IMG_SIZE, IMG_SIZE), Image.LANCZOS)
                images.append(np.array(img).astype('float32') / 255.0)
    return np.array(images)[..., np.newaxis]  # (N, 128, 128, 1)

train_dir = os.path.join(path, 'chest_xray', 'train')
test_dir  = os.path.join(path, 'chest_xray', 'test')
val_dir   = os.path.join(path, 'chest_xray', 'val')

x_train = load_images(train_dir)
x_test  = load_images(test_dir)
x_val   = load_images(val_dir)

# Merge tiny val split (16 images) into test
x_test = np.concatenate([x_test, x_val], axis=0)

print(f"Train : {x_train.shape}  |  range: [{x_train.min():.2f}, {x_train.max():.2f}]")
print(f"Test  : {x_test.shape}   |  range: [{x_test.min():.2f}, {x_test.max():.2f}]")
print(f"Total : {len(x_train) + len(x_test)} images at {IMG_SIZE}×{IMG_SIZE}")

# =====================================================================
# CELL 5 — Data Augmentation
# =====================================================================
# With only 5,856 training images, augmentation is critical.
# We apply random transformations to effectively 3× the dataset,
# giving the model more diverse anatomical patterns to learn from.

def augment_batch(images):
    """Apply random augmentations: flip, rotation, brightness, contrast."""
    augmented = []
    for img in images:
        h, w = img.shape[0], img.shape[1]
        # Random horizontal flip (anatomically valid for chest X-rays)
        if np.random.random() > 0.5:
            img = img[:, ::-1, :]
        # Random brightness adjustment (±15%)
        factor = np.random.uniform(0.85, 1.15)
        img = np.clip(img * factor, 0, 1)
        # Random contrast adjustment (±10%)
        mean = np.mean(img)
        contrast = np.random.uniform(0.9, 1.1)
        img = np.clip((img - mean) * contrast + mean, 0, 1)
        augmented.append(img)
    return np.array(augmented)

# Create two augmented copies of training data
x_train_aug1 = augment_batch(x_train)
x_train_aug2 = augment_batch(x_train)
x_train_full = np.concatenate([x_train, x_train_aug1, x_train_aug2], axis=0)

# Shuffle
shuffle_idx = np.random.permutation(len(x_train_full))
x_train_full = x_train_full[shuffle_idx]

print(f"Original training set : {len(x_train)} images")
print(f"After augmentation   : {len(x_train_full)} images (3×)")

# =====================================================================
# CELL 6 — Noise Functions
# =====================================================================
#
# DENOISING PRINCIPLE:
# We corrupt clean X-rays with synthetic noise and train the model to
# recover the clean version. The model cannot memorize — it MUST learn
# what real anatomy looks like to fill in what the noise destroyed.
#
# MIXED NOISE TRAINING makes the model robust to different corruption
# patterns encountered in real clinical settings.

def add_gaussian_noise(images, noise_factor=0.3):
    """Quantum noise / electronic noise in X-ray detectors."""
    noise = noise_factor * np.random.normal(size=images.shape)
    return np.clip(images + noise, 0.0, 1.0)

def add_salt_pepper(images, amount=0.06):
    """Dead/hot pixels in flat-panel X-ray detectors."""
    noisy = images.copy()
    salt_mask = np.random.random(images.shape) < (amount / 2)
    noisy[salt_mask] = 1.0
    pepper_mask = np.random.random(images.shape) < (amount / 2)
    noisy[pepper_mask] = 0.0
    return noisy

def add_block_corruption(images, block_size=10, n_blocks=8):
    """PACS transmission errors / DICOM file corruption."""
    noisy = images.copy()
    h, w = images.shape[1], images.shape[2]
    for img in noisy:
        for _ in range(n_blocks):
            y = np.random.randint(0, h - block_size)
            x = np.random.randint(0, w - block_size)
            img[y:y+block_size, x:x+block_size] = 0.0
    return noisy

def add_mixed_noise(images):
    """Randomly apply one of three noise types to each image."""
    noisy = images.copy()
    n = len(images)
    indices = np.arange(n)
    np.random.shuffle(indices)
    third = n // 3
    # 1/3 Gaussian (varying σ)
    for i in indices[:third]:
        sigma = np.random.uniform(0.15, 0.45)
        noisy[i] = np.clip(images[i] + sigma * np.random.normal(size=images[i].shape), 0, 1)
    # 1/3 Salt & Pepper (varying amount)
    for i in indices[third:2*third]:
        amt = np.random.uniform(0.03, 0.10)
        noisy[i] = add_salt_pepper(images[i:i+1], amount=amt)[0]
    # 1/3 Block corruption (varying size)
    for i in indices[2*third:]:
        bs = np.random.randint(6, 14)
        nb = np.random.randint(5, 12)
        noisy[i] = add_block_corruption(images[i:i+1], block_size=bs, n_blocks=nb)[0]
    return noisy

# Create noisy training data (mixed)
x_train_noisy = add_mixed_noise(x_train_full)

# Test sets: one per noise type for separate evaluation
NOISE_FACTOR = 0.3
x_test_gaussian = add_gaussian_noise(x_test, NOISE_FACTOR)
x_test_sp       = add_salt_pepper(x_test, amount=0.06)
x_test_block    = add_block_corruption(x_test)

print(f"Training noise: MIXED (Gaussian + Salt&Pepper + Block)")
print(f"Training pairs: {len(x_train_full)} noisy → clean")

# =====================================================================
# CELL 7 — Visualize Noise Types
# =====================================================================
fig, axes = plt.subplots(4, 6, figsize=(16, 10))
fig.suptitle("Noise Types Applied to Chest X-Rays", fontsize=14, fontweight='bold')

vis_data = [
    ("Clean Original",       x_test),
    (f"Gaussian (σ={NOISE_FACTOR})", x_test_gaussian),
    ("Salt & Pepper (6%)",   x_test_sp),
    ("Block Corruption",     x_test_block),
]

for row, (label, imgs) in enumerate(vis_data):
    axes[row, 0].set_ylabel(label, fontsize=10, rotation=0, labelpad=100, va='center')
    for col in range(6):
        axes[row, col].imshow(imgs[col].squeeze(), cmap='gray', vmin=0, vmax=1)
        axes[row, col].axis('off')

plt.tight_layout()
plt.savefig('noise_types_xray.png', dpi=150, bbox_inches='tight')
plt.show()

# =====================================================================
# CELL 8 — Mathematical Modeling (Markdown Cell in Colab)
# =====================================================================
"""
## Mathematical Modeling

**Architecture**: U-Net Denoising Autoencoder (Encoder-Decoder with Skip Connections)

**Why Skip Connections?**
In a standard autoencoder, ALL information passes through a narrow bottleneck:
  x̂ = g_φ(f_θ(x̃))

Fine details (rib edges, hairline fractures) are lost because the bottleneck
cannot preserve them. A U-Net adds skip connections that concatenate encoder
feature maps directly to decoder layers:

  d_i = g_i(concat(d_{i-1}, e_i))

where e_i is the encoder output at level i. This lets the decoder access
high-resolution features directly, so it only needs to learn the RESIDUAL
difference rather than reconstructing everything from the bottleneck.

**Loss Function**: Combined MSE + SSIM Loss
  L = α · MSE(x, x̂) + (1 - α) · (1 - SSIM(x, x̂))

where α = 0.5. MSE ensures pixel-level accuracy. SSIM preserves structural
similarity (edges, textures, luminance) — critical for medical images where
radiologists rely on structural features for diagnosis.

**Optimization**: Adam (lr=1e-3) with ReduceLROnPlateau and EarlyStopping

**Evaluation Metrics**:
- PSNR: higher = better (dB). Every +3 dB ≈ 2× quality
- SSIM: 0→1, measures structural preservation
- Pixel Accuracy: % of pixels within τ=0.1 of clean original
"""

# =====================================================================
# CELL 9 — Custom SSIM+MSE Loss Function
# =====================================================================
def ssim_loss(y_true, y_pred):
    """
    Structural Similarity loss.
    SSIM measures perceptual image quality based on luminance, contrast,
    and structure — the exact features radiologists evaluate.
    Returns 1 - SSIM so that lower loss = better structure preservation.
    """
    return 1.0 - tf.reduce_mean(
        tf.image.ssim(y_true, y_pred, max_val=1.0)
    )

def combined_loss(y_true, y_pred):
    """
    50% MSE + 50% (1 - SSIM)
    MSE handles pixel accuracy. SSIM handles structural sharpness.
    Together they produce cleaner, sharper reconstructions than either alone.
    """
    mse = tf.reduce_mean(tf.square(y_true - y_pred))
    ssim_l = ssim_loss(y_true, y_pred)
    return 0.5 * mse + 0.5 * ssim_l

# Custom metric to track SSIM during training
def ssim_metric(y_true, y_pred):
    return tf.reduce_mean(tf.image.ssim(y_true, y_pred, max_val=1.0))

# =====================================================================
# CELL 10 — Build U-Net Denoising Model
# =====================================================================
#
# U-NET ARCHITECTURE for 128×128 grayscale X-rays:
#
# ENCODER (contracting path):
#   128×128×1  → [Conv32×2 + BN] → skip1 → Pool → 64×64×32
#   64×64×32   → [Conv64×2 + BN] → skip2 → Pool → 32×32×64
#   32×32×64   → [Conv128×2 + BN + Dropout] → BOTTLENECK (32×32×128)
#
# DECODER (expanding path):
#   32×32×128  → Up → 64×64×128 → concat(skip2) → 64×64×192 → [Conv64×2]
#   64×64×64   → Up → 128×128×64 → concat(skip1) → 128×128×96 → [Conv32×2]
#   → Conv1 (sigmoid) → 128×128×1
#
# Skip connections carry encoder features directly to the decoder,
# preserving fine anatomical detail that the bottleneck would destroy.

def conv_block(x, filters, name_prefix, dropout=0.0):
    """Two Conv2D + BN + ReLU layers, optionally with Dropout."""
    x = Conv2D(filters, (3,3), padding='same', name=f'{name_prefix}_conv1')(x)
    x = BatchNormalization(name=f'{name_prefix}_bn1')(x)
    x = Activation('relu')(x)
    x = Conv2D(filters, (3,3), padding='same', name=f'{name_prefix}_conv2')(x)
    x = BatchNormalization(name=f'{name_prefix}_bn2')(x)
    x = Activation('relu')(x)
    if dropout > 0:
        x = Dropout(dropout, name=f'{name_prefix}_dropout')(x)
    return x

def build_unet_denoiser():
    inputs = Input(shape=(IMG_SIZE, IMG_SIZE, 1), name='noisy_xray_input')

    # ── ENCODER ──────────────────────────────────────────────────────
    # Level 1: 128×128 → 64×64
    enc1 = conv_block(inputs, 32, 'enc1')                    # 128×128×32
    pool1 = MaxPooling2D((2,2), name='pool1')(enc1)           # 64×64×32

    # Level 2: 64×64 → 32×32
    enc2 = conv_block(pool1, 64, 'enc2')                     # 64×64×64
    pool2 = MaxPooling2D((2,2), name='pool2')(enc2)           # 32×32×64

    # Level 3 (Bottleneck): 32×32
    bottleneck = conv_block(pool2, 128, 'bottleneck', dropout=0.15)  # 32×32×128

    # ── DECODER with Skip Connections ────────────────────────────────
    # Level 2: 32×32 → 64×64
    up2 = UpSampling2D((2,2), name='up2')(bottleneck)         # 64×64×128
    merge2 = Concatenate(name='skip2')([up2, enc2])           # 64×64×(128+64)=192
    dec2 = conv_block(merge2, 64, 'dec2')                     # 64×64×64

    # Level 1: 64×64 → 128×128
    up1 = UpSampling2D((2,2), name='up1')(dec2)               # 128×128×64
    merge1 = Concatenate(name='skip1')([up1, enc1])           # 128×128×(64+32)=96
    dec1 = conv_block(merge1, 32, 'dec1')                     # 128×128×32

    # Output: sigmoid for pixel intensities in [0, 1]
    outputs = Conv2D(1, (1,1), activation='sigmoid',
                     name='output_reconstruction')(dec1)       # 128×128×1

    model = Model(inputs, outputs, name='unet_medical_denoiser')
    model.compile(
        optimizer=tf.keras.optimizers.Adam(learning_rate=1e-3),
        loss=combined_loss,
        metrics=['mae', ssim_metric]
    )
    return model

autoencoder = build_unet_denoiser()
autoencoder.summary()

total_params = autoencoder.count_params()
bottleneck_size = (IMG_SIZE//4) * (IMG_SIZE//4) * 128
input_size = IMG_SIZE * IMG_SIZE

print(f"\nTotal parameters  : {total_params:,}")
print(f"Bottleneck size   : {IMG_SIZE//4}×{IMG_SIZE//4}×128 = {bottleneck_size:,} values")
print(f"Input size        : {IMG_SIZE}×{IMG_SIZE}×1 = {input_size:,} values")
print(f"Architecture      : U-Net with skip connections")
print(f"Loss function     : 0.5×MSE + 0.5×(1-SSIM)")

# =====================================================================
# CELL 11 — Train the Model
# =====================================================================
EPOCHS = 50
BATCH_SIZE = 16   # smaller batch → more gradient updates per epoch

callbacks = [
    EarlyStopping(
        monitor='val_loss', patience=10,
        restore_best_weights=True, verbose=1
    ),
    ReduceLROnPlateau(
        monitor='val_loss', factor=0.5,
        patience=5, min_lr=1e-6, verbose=1
    ),
    ModelCheckpoint(
        'best_unet_denoiser.h5', monitor='val_loss',
        save_best_only=True, verbose=1
    )
]

# Validation with Gaussian noise (consistent benchmark)
x_val_noisy = add_gaussian_noise(x_test, NOISE_FACTOR)

history = autoencoder.fit(
    x_train_noisy, x_train_full,     # input = noisy, target = clean
    epochs=EPOCHS,
    batch_size=BATCH_SIZE,
    validation_data=(x_val_noisy, x_test),
    callbacks=callbacks,
    verbose=1
)

final_epoch = len(history.history['loss'])
print(f"\nTraining complete after {final_epoch} epochs.")
print(f"Best val_loss: {min(history.history['val_loss']):.6f}")

# =====================================================================
# CELL 12 — Training History
# =====================================================================
fig, axes = plt.subplots(1, 3, figsize=(18, 5))

axes[0].plot(history.history['loss'],     label='Train', color='#00d4ff', linewidth=1.5)
axes[0].plot(history.history['val_loss'], label='Val',   color='#ff6b6b', linewidth=1.5)
axes[0].set_title('Combined Loss (MSE + SSIM)', fontweight='bold')
axes[0].set_xlabel('Epoch'); axes[0].set_ylabel('Loss')
axes[0].legend(); axes[0].grid(alpha=0.3)

axes[1].plot(history.history['mae'],     label='Train', color='#00d4ff', linewidth=1.5)
axes[1].plot(history.history['val_mae'], label='Val',   color='#ff6b6b', linewidth=1.5)
axes[1].set_title('Mean Absolute Error', fontweight='bold')
axes[1].set_xlabel('Epoch'); axes[1].set_ylabel('MAE')
axes[1].legend(); axes[1].grid(alpha=0.3)

axes[2].plot(history.history['ssim_metric'],     label='Train', color='#00d4ff', linewidth=1.5)
axes[2].plot(history.history['val_ssim_metric'], label='Val',   color='#ff6b6b', linewidth=1.5)
axes[2].set_title('SSIM Score (↑ better)', fontweight='bold')
axes[2].set_xlabel('Epoch'); axes[2].set_ylabel('SSIM')
axes[2].set_ylim(0, 1)
axes[2].legend(); axes[2].grid(alpha=0.3)

plt.suptitle('Training History — U-Net Medical Image Denoiser', fontweight='bold', fontsize=14)
plt.tight_layout()
plt.savefig('training_history.png', dpi=150, bbox_inches='tight')
plt.show()

# =====================================================================
# CELL 13 — Comprehensive Evaluation
# =====================================================================
def evaluate_on_noise(clean, noisy, model, noise_name):
    """Evaluate denoising quality on a specific noise type."""
    denoised = model.predict(noisy, verbose=0)
    denoised = np.clip(denoised, 0.0, 1.0)
    n = len(clean)

    psnr_n = np.mean([psnr(clean[i].squeeze(), noisy[i].squeeze(), data_range=1.0) for i in range(n)])
    psnr_d = np.mean([psnr(clean[i].squeeze(), denoised[i].squeeze(), data_range=1.0) for i in range(n)])
    ssim_n = np.mean([ssim(clean[i].squeeze(), noisy[i].squeeze(), data_range=1.0) for i in range(n)])
    ssim_d = np.mean([ssim(clean[i].squeeze(), denoised[i].squeeze(), data_range=1.0) for i in range(n)])
    mse_n  = float(np.mean((clean - noisy)**2))
    mse_d  = float(np.mean((clean - denoised)**2))
    noise_reduction = (1 - mse_d / mse_n) * 100
    pixel_acc = float(np.mean(np.abs(clean - denoised) < 0.1) * 100)

    return {
        'noise_type': noise_name,
        'psnr_noisy': round(psnr_n, 2), 'psnr_denoised': round(psnr_d, 2),
        'psnr_gain': round(psnr_d - psnr_n, 2),
        'ssim_noisy': round(ssim_n, 4), 'ssim_denoised': round(ssim_d, 4),
        'ssim_gain': round(ssim_d - ssim_n, 4),
        'mse_noisy': round(mse_n, 6), 'mse_denoised': round(mse_d, 6),
        'noise_reduction_pct': round(noise_reduction, 1),
        'pixel_accuracy': round(pixel_acc, 1),
    }, denoised

# Evaluate on all three noise types
results_gauss, dn_gauss  = evaluate_on_noise(x_test, x_test_gaussian, autoencoder, "Gaussian (σ=0.3)")
results_sp, dn_sp        = evaluate_on_noise(x_test, x_test_sp, autoencoder, "Salt & Pepper (6%)")
results_block, dn_block  = evaluate_on_noise(x_test, x_test_block, autoencoder, "Block Corruption")

all_results = [results_gauss, results_sp, results_block]

print("=" * 95)
print(f"  U-NET MEDICAL IMAGE DENOISING — EVALUATION REPORT")
print(f"  Architecture: U-Net (skip connections) | Loss: MSE+SSIM | Dataset: Kaggle Chest X-Ray")
print(f"  Resolution: {IMG_SIZE}×{IMG_SIZE} | Test samples: {len(x_test)} per noise type")
print("=" * 95)
print(f"{'Noise Type':<22} {'PSNR Before':>11} {'PSNR After':>11} {'Gain':>8} {'SSIM Before':>12} {'SSIM After':>11} {'Noise Removed':>14} {'Px Acc':>8}")
print("-" * 95)
for r in all_results:
    print(f"{r['noise_type']:<22} {r['psnr_noisy']:>11.2f} {r['psnr_denoised']:>11.2f} {r['psnr_gain']:>+8.2f} "
          f"{r['ssim_noisy']:>12.4f} {r['ssim_denoised']:>11.4f} {r['noise_reduction_pct']:>13.1f}% {r['pixel_accuracy']:>7.1f}%")
print("=" * 95)

# =====================================================================
# CELL 14 — Visualize Denoising Results
# =====================================================================
def show_results(clean, noisy, denoised, n=8, title="Results"):
    fig, axes = plt.subplots(3, n, figsize=(2*n, 6.5))
    fig.suptitle(title, fontsize=14, fontweight='bold')
    row_labels = ['Clean X-Ray', 'Noisy Input', 'U-Net Output']
    for row, (imgs, label) in enumerate(zip([clean, noisy, denoised], row_labels)):
        axes[row, 0].set_ylabel(label, fontsize=10, rotation=0, labelpad=80, va='center')
        for col in range(n):
            axes[row, col].imshow(np.clip(imgs[col].squeeze(), 0, 1), cmap='gray', vmin=0, vmax=1)
            axes[row, col].axis('off')
            if row == 0:
                p = psnr(clean[col].squeeze(), denoised[col].squeeze(), data_range=1.0)
                axes[0, col].set_title(f'PSNR: {p:.1f}', fontsize=8, color='#22c55e')
    plt.tight_layout()
    fname = title.lower().replace(' ', '_').replace('(', '').replace(')', '') + '.png'
    plt.savefig(fname, dpi=150, bbox_inches='tight')
    plt.show()

show_results(x_test, x_test_gaussian, dn_gauss, title="Gaussian Noise (σ=0.3)")
show_results(x_test, x_test_sp, dn_sp, title="Salt and Pepper (Generalization)")
show_results(x_test, x_test_block, dn_block, title="Block Corruption (Generalization)")

# =====================================================================
# CELL 15 — Error Heatmaps
# =====================================================================
fig, axes = plt.subplots(3, 8, figsize=(18, 7))
fig.suptitle("Reconstruction Error Heatmaps — |x_clean − x̂|", fontsize=14, fontweight='bold')

for row, (denoised, label) in enumerate([
    (dn_gauss, "Gaussian"), (dn_sp, "Salt & Pepper"), (dn_block, "Block Corruption")
]):
    axes[row, 0].set_ylabel(label, fontsize=10, rotation=0, labelpad=80, va='center')
    for col in range(8):
        error = np.abs(x_test[col].squeeze() - denoised[col].squeeze())
        axes[row, col].imshow(error, cmap='hot', vmin=0, vmax=0.3)
        axes[row, col].axis('off')

plt.tight_layout()
plt.savefig('error_heatmaps.png', dpi=150, bbox_inches='tight')
plt.show()

# =====================================================================
# CELL 16 — Metric Comparison Charts
# =====================================================================
fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(14, 5))
noise_names = [r['noise_type'] for r in all_results]
x_pos = np.arange(len(noise_names))
width = 0.35

bars1 = ax1.bar(x_pos - width/2, [r['psnr_noisy'] for r in all_results], width,
                label='Before', color='#f87171', alpha=0.85)
bars2 = ax1.bar(x_pos + width/2, [r['psnr_denoised'] for r in all_results], width,
                label='After', color='#34d399', alpha=0.85)
ax1.set_ylabel('PSNR (dB)'); ax1.set_title('PSNR — Higher is Better', fontweight='bold')
ax1.set_xticks(x_pos); ax1.set_xticklabels(noise_names, fontsize=9)
ax1.legend(); ax1.grid(axis='y', alpha=0.3)
for bar in bars1 + bars2:
    ax1.text(bar.get_x() + bar.get_width()/2, bar.get_height() + 0.3,
             f'{bar.get_height():.1f}', ha='center', fontsize=8)

bars3 = ax2.bar(x_pos - width/2, [r['ssim_noisy'] for r in all_results], width,
                label='Before', color='#f87171', alpha=0.85)
bars4 = ax2.bar(x_pos + width/2, [r['ssim_denoised'] for r in all_results], width,
                label='After', color='#34d399', alpha=0.85)
ax2.set_ylabel('SSIM'); ax2.set_title('SSIM — Higher is Better', fontweight='bold')
ax2.set_xticks(x_pos); ax2.set_xticklabels(noise_names, fontsize=9)
ax2.set_ylim(0, 1); ax2.legend(); ax2.grid(axis='y', alpha=0.3)
for bar in bars3 + bars4:
    ax2.text(bar.get_x() + bar.get_width()/2, bar.get_height() + 0.01,
             f'{bar.get_height():.3f}', ha='center', fontsize=8)

plt.suptitle('U-Net Denoising Performance', fontweight='bold', fontsize=14)
plt.tight_layout()
plt.savefig('metric_comparison.png', dpi=150, bbox_inches='tight')
plt.show()

# =====================================================================
# CELL 17 — Save Model and Metrics
# =====================================================================
autoencoder.save('denoising_autoencoder.h5')

metrics = {
    'model_name':       'unet_medical_denoiser',
    'input_size':       f'{IMG_SIZE}×{IMG_SIZE}×1',
    'bottleneck':       f'{IMG_SIZE//4}×{IMG_SIZE//4}×128 = {bottleneck_size:,} values',
    'compression_ratio': round(input_size / bottleneck_size, 4),
    'total_params':     total_params,
    'architecture':     f'U-Net: {IMG_SIZE}×{IMG_SIZE}×1 → [Conv32×2+BN] → Pool(skip1) → [Conv64×2+BN] → Pool(skip2) → [Conv128×2+BN+Drop] → Up+skip2 → [Conv64×2] → Up+skip1 → [Conv32×2] → Conv1(sigmoid)',
    'skip_connections': True,
    'training': {
        'epochs_run':    final_epoch,
        'batch_size':    BATCH_SIZE,
        'optimizer':     'Adam (lr=1e-3)',
        'loss':          '0.5*MSE + 0.5*(1-SSIM)',
        'noise_type':    'Mixed (Gaussian + Salt&Pepper + Block)',
        'augmentation':  '3× (flip, brightness, contrast)',
        'training_images': len(x_train_full),
        'best_val_loss': round(float(min(history.history['val_loss'])), 6),
    },
    'dataset': {
        'name':          'Kaggle Chest X-Ray Pneumonia',
        'source':        'Guangzhou Women and Children\'s Medical Center',
        'train_images':  len(x_train),
        'test_images':   len(x_test),
        'resolution':    f'{IMG_SIZE}×{IMG_SIZE} grayscale',
    },
    'evaluation': {
        'gaussian':      results_gauss,
        'salt_pepper':   results_sp,
        'block_corrupt': results_block,
    }
}

with open('metrics.json', 'w') as f:
    json.dump(metrics, f, indent=2)

print("=" * 50)
print("Saved: denoising_autoencoder.h5")
print("Saved: metrics.json")
print("=" * 50)
print(json.dumps(metrics, indent=2))

# =====================================================================
# CELL 18 — Download from Colab
# =====================================================================
from google.colab import files
files.download('denoising_autoencoder.h5')
files.download('metrics.json')
